version: '3.9'
services:
  cache:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - ${APP_PORT}:6379
    networks:
      - default
    volumes:
      - /root/redis/data:/data
    command:
      - --requirepass password

networks:
  default:
    driver: bridge

volumes:
  data:
    driver: local
